defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: "docs"
    values:
      layout: docs
      tab: docs

sass:
  sass_dir: _sass
  style: :compressed

baseurl: "/metronome"
highlighter: rouge
lsi: false
markdown: kramdown
safe: true
source: .
